name: Reproduce 1

on: workflow_dispatch

jobs:
  reproduce:
    name: Reproduce
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
